### ISSUE TITLE
Buttons not visible with starryNight theme

### ISSUE THREAD

**Issue by IMT07** [theRealPadster/name-that-tune#105]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
im using the latest versions of spotify, spicetify and the app
```

### 📝 Description

the buttons from the app are not visible with StarryNight Theme

### 📸 Screenshots

![image](https://github.com/theRealPadster/name-that-tune/assets/81577133/35904da9-d491-4f80-b6d6-6b5a0d5e4ee5)

**Comment by sanoojes** [comment]
i think thats related to theme

**Comment by theRealPadster** [comment]
Yeah that looks to me like the theme is changing the colour of the buttons to white but not correctly changing the text colour so it's readable here. Theme would likely need to be updated to properly apply to the buttons on this page.

**Comment by theRealPadster** [comment]
Yeah that looks to me like the theme is changing the colour of the buttons to white but not correctly changing the text colour so it's readable here. Theme would likely need to be updated to properly apply to the buttons on this page.
