### ISSUE TITLE
Track how many you got right

### ISSUE THREAD

**Issue by IMT07** [theRealPadster/name-that-tune#106]
### 📝 Provide a description of the new feature

It would be cool if you could see how many you got right 1st try or smth like that, and maybe multiplayer support as well?

**Comment by theRealPadster** [comment]
There's a stats section that shows how many you got at various guess amounts

**Comment by IMT07** [comment]
Where do I find these stats?

**Comment by theRealPadster** [comment]
> Where do I find these stats?

Bottom right (I think?) corner of the game page there's a "stats" button
