### ISSUE TITLE
Normalize strings

### ISSUE THREAD

**Issue by zdimension** [theRealPadster/name-that-tune#112]
### 📝 Provide a description of the new feature

There is a song called `Le Dîner` (note the diacritic on the i). `Le Diner` should be an accepted input for that song.

Normalizing the string to NFD and then removing the diacritic combining characters should do the trick, see [here](https://stackoverflow.com/a/37511463/2196124).

**Comment by theRealPadster** [comment]
Thanks, works like a charm. Published new release with this update.
