### ISSUE TITLE
Come up with a better name

### ISSUE THREAD

**Issue by theRealPadster** [theRealPadster/name-that-tune#16]
### 📝 Provide a description of the new feature

Spurdle is an awful name

**Comment by Satanarious** [comment]
I googled 'song guessing' and the first thing that came up was 'Song Trivia'. **Spotrivia** was the first thing that came to mind as soon as I saw that.

**Comment by theRealPadster** [comment]
Ah, I do like the "guessing" theme more than "trivia", since "trivia" sound more like facts to me, rather than just the song names. Maybe SpotiGuesser, kind of like GeoGuesser?

**Comment by theRealPadster** [comment]
I decided something more generic like "Name That Tune" might be a better idea than trying to combine words together.
