### ISSUE TITLE
Add leaderboard

### ISSUE THREAD

**Issue by CharlieS1103** [theRealPadster/name-that-tune#20]
### 📝 Provide a description of the new feature

Pretty standard leaderboard system.

**Comment by theRealPadster** [comment]
Uh wat?

**Comment by CharlieS1103** [comment]
@theRealPadster I decided to just close a few of my issues/prs just for the sake of organizing things. I can reopen it if you'd like.

**Comment by theRealPadster** [comment]
It's not a bad idea. Idk how I'd implement it. If you don't really care about the feature you can leave it closed. Was just confused cause it said "closed as completed" and I haven't touched this app in months.
