### ISSUE TITLE
unistall custom app

### ISSUE THREAD

**Issue by fvkd4n** [theRealPadster/name-that-tune#24]
### 🔍 Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.93.896.g3ae3b4f3
- Spicetify version: 2.13.0
```

### 📝 Description

Hi, when I click on the custom app it gives me an error "there was a problem, try to reload the page" I also tried with "name-that-tune-main" but nothing was solved and I tried to uninstall both custom app but I don't know how to do it. :(

### 📸 Screenshots

https://i.imgur.com/J6DRYdp.png

**Comment by theRealPadster** [comment]
Main won't work. Needs to be dist branch. If you want to uninstall, you can remove the custom app from your config and re-run spicetify apply, like any other custom app or extension.

**Comment by fvkd4n** [comment]
I tried to reinstall everything and in the end it worked but I tried to remove the folder from CustomApps and run the command but it gives me this error (the error is in the photo) and the custom app always remains there
![explorer_6tFMCrtJmO](https://user-images.githubusercontent.com/74561257/188886588-204d622f-b565-41a3-85e4-7757b96f0147.png)
![xBYBmxP0tQ](https://user-images.githubusercontent.com/74561257/188886883-4d2728b0-ab1a-456a-8476-0bca6eacf1f5.png)

**Comment by theRealPadster** [comment]
Open your config file and manually remove it. It may be called "spurdle" as that was the original name. 
If you're not sure, just post the custom apps line from your config file here and I can help.

**Comment by fvkd4n** [comment]
1 (.spicetify folder ) : https://i.imgur.com/6Lnv2sX.png
2 (name-that-tune-dist folder): https://i.imgur.com/UArAOZd.png

**Comment by fvkd4n** [comment]
Surely I was wrong, this image should be the right one
![powershell_ubTmurXpLR](https://user-images.githubusercontent.com/74561257/189177701-eb02ef9f-cb24-45e2-b459-16ee6ec8423c.png)

**Comment by S0Iomon** [comment]
I got it

Go to `C:\Users\{Username}\AppData\Roaming\spicetify`

you will find `config-xpui`

to uninstall:
go to `[AdditionalOptions]`
then remove `name-that-tune-dist`
lastly, `spicetify apply`

**Comment by theRealPadster** [comment]
Yes, that's essentially what I said, isn't it? Open config file and remove it (whatever you have the folder called)

**Comment by S0Iomon** [comment]
thing is, you said spurdle...
"It may be called "spurdle" as that was the original name."

so what I did is just to clarify 'cause even I do not know where the config is.
