### ISSUE TITLE
Linux showing what's playing

### ISSUE THREAD

**Issue by Flyingbacen** [theRealPadster/name-that-tune#25]
If you're on Linux, (I'm on Mint, but I'd assume it'd be the same for other distros), then it shows a notification of what's playing when you go to the next song. Would it be possible for you to disable the notification that pops up?
![Screenshot at 2022-11-10 18-46-00](https://user-images.githubusercontent.com/73092546/201239278-2283c40e-9b15-44bd-8bde-7c160083d87c.png)

**Comment by theRealPadster** [comment]
Not possible. Pretty sure that's Spotify sending the standard MPRIS media daemon notification, which I don't believe we have any control over in the JS. That would be internal app logic and probably can't be changed. You could potentially turn on do not disturb while you play, to disable popup notifications, if that's a feature in Linux Mint? I know that's an option on GNOME-Shell.  

Also, it looks like you've got the Dribbblish Dynamic extension enabled but aren't using the theme, which is causing your playlists to look messed up. You may want to remove the extension. Just a tip.

**Comment by Flyingbacen** [comment]
turns out I was dummb, and if I had done a bit of searching, I could turn it off, but eh
![image](https://user-images.githubusercontent.com/73092546/204075550-1aeea884-fc3b-4bc1-9025-013fa1e6bd72.png)
also, I've just reapplied spicetify since then, but thank you for that if I somehow do that again, _not sure how I did it in the first place xp_
