### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by tastemasauce** [theRealPadster/name-that-tune#27]
### 📝 Provide a description of the new feature

There is no support for foreign languages, it's not relevant for me, so ... How to uninstall?

**Comment by theRealPadster** [comment]
I can add localization support. To uninstall, just do the opposite of the install steps. Remove from the custom apps folder, remove from config file, and reapply spicetify.

**Comment by theRealPadster** [comment]
@tastemasauce Just added translation support :) 
Feel free to add your native language. Instructions here: https://github.com/theRealPadster/name-that-tune#translations
