### ISSUE TITLE
"something went wrong.. try to reload the site"

### ISSUE THREAD

**Issue by pqul187** [theRealPadster/name-that-tune#31]
everytime when i press on "Name-that-tune" on the left menu, there comes up an message: "something went wrong.. try to reload the site".

how can i play?

**Comment by pqul187** [comment]
So i did it again and now when i download the dist branch again and put in the codes, powershell tells me "Custom App name-that-tune does not have index.js" even though it is in the folder. What do I have to do now?

**Comment by theRealPadster** [comment]
Your folder structure is probably wrong. That file should  be located at customapps/name-that-tune/index.js

**Comment by pqul187** [comment]
it was located there

but now i fixed it, i reinstallied spotify, spicetify and name that tune and now it works
