### ISSUE TITLE
Traduccion Español

### ISSUE THREAD

**Issue by Alex-mdx** [theRealPadster/name-that-tune#33]
### What language are you adding?

Español Latino

### Translation JSON

{
  "translation": {
    "appName": "Nombra la Rola",
    "title": "🎵 $t(appName)",
    "winMsg": "Ganaste!",
    "guessPlaceholder": "Adivina la canción",
    "playXSeconds": "Reproducir {{count}}s",
    "guessBtn": "Adivinar",
    "skipBtn": "Saltar",
    "giveUp": "Rendirse",
    "nextSong": "Siguiente Canción",
    "menuEntry": "Reproducir $t(appName)",
    "sendingURIs_one": "Enviando {{count}} URI a $t(appName)",
    "sendingURIs_other": "Enviando {{count}} URIs a $t(appName)",
    "stats": {
      "title": "Estatus",
      "time": "Tiempo",
      "songs": "Canciones",
      "winPercentage": "Ganar con porcentaje: {{percentage}}%",
      "songWithCount_one": "{{count}} Cancion(es)",
      "songWithCount_other": "{{count}} Canción(es)",
      "gaveUp": "Rendiciones",
      "greaterThan16": ">16s",
      "xSeconds": "{{count}}s"
    }
  }
}

**Comment by theRealPadster** [comment]
Thanks! I've added. Please give it a try and let me know if there is anything that should be adjusted.

**Comment by Alex-mdx** [comment]
yes its works correctly!!!
[image: image.png]
