### ISSUE TITLE
"Something went wrong" "try to refresh the page"

### ISSUE THREAD

**Issue by LucasSnowx** [theRealPadster/name-that-tune#36]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.7.1277.g2b3ce637
- Spicetify version: v2.16.2
```

### 📝 Description

The problem could be that my spotify is hungarian, but idk how to make name that tune to english, cause i dont understand the way of the language change...

**Comment by ChromaPIE** [comment]
Spotify Windows
- Spotify version: 1.2.8.923.g4f94bf0d
- Spicetify v2.17.0

Same issue, but the error already happened when installing the custom app. `error Custom app "name-that-tune" not found.` was displayed on the shell.

**Comment by theRealPadster** [comment]
> Spotify Windows
> 
>     * Spotify version: 1.2.8.923.g4f94bf0d
> 
>     * Spicetify v2.17.0
> 
> 
> Same issue, but the error already happened when installing the custom app. `error Custom app "name-that-tune" not found.` was displayed on the shell.

This error means you didn't install it correctly. Please follow the directions in the readme.

**Comment by DefeatedCoot** [comment]
> If the language you're using is missing, it should fall back to English. Can you test other custom apps and see if they work? That would help determine if it's an issue with Name That Tune, or just a configuration/compatibility issue.

This issue is happening to me as well, but stats and other apps work fine.

**Comment by theRealPadster** [comment]
> This issue is happening to me as well, but stats and other apps work fine.

Can you confirm you've got it set up the exact same way as the other custom apps? e.g. your config-xpui.ini file has the name of the custom app as the parent folder with the index.js inside it?

**Comment by tenkuu23** [comment]
> 

the folder doesn't have the index.js inside

**Comment by theRealPadster** [comment]
> > 
> 
> the folder doesn't have the index.js inside

If the folder doesn't have the index.js, then you haven't installed it correctly. Please use the dist branch, as per the [installation instructions](https://github.com/theRealPadster/name-that-tune#installation)

**Comment by tenkuu23** [comment]
> @tenkuu23
> 
> > the folder doesn't have the index.js inside
> 
> If the folder doesn't have the index.js, then you haven't installed it correctly. Please use the dist branch, as per the [installation instructions](https://github.com/theRealPadster/name-that-tune#installation)

oh thanks, now it works <3
