### ISSUE TITLE
Add Option to Extend the Listening Time Beyond 1 Second

### ISSUE THREAD

**Issue by andrewcincotta** [theRealPadster/name-that-tune#39]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.9
- Spicetify version: 2.17.2
```

### 📝 Description

Where can I access the listening time?

**Comment by theRealPadster** [comment]
If you make a guess or skip, it gives you more time. Is something not working?
