### ISSUE TITLE
"something went wrong.. try to reload the site"

### ISSUE THREAD

**Issue by Yusuf-Duran** [theRealPadster/name-that-tune#51]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.22.982.g794acc0a
- Spicetify version: 2.23.2
- OS: Windows 11
```

### 📝 Description

1. Install spotify
2. Add spicetify
3. install name-that-tune
4. try opening the Name That Tune tab (see screenshots for before after this step)
5. "something went wrong.. try to reload the site"

Both Spotify and spicetify are newly installed on this becuase I accidentally switched from desktop version to windows store version. So I switched back to desktop version by uninstalling the windows store version and instalilng the desktop version with a freshly downloaded installer file from the spotify website. Had to apply spicetify again and all my configuration seems to have gotten lost in the progress. So I reapplied all the plugins I wanted and then tried this custom app just for it to not work. I checked out the previous issues and the ones having a similar error to mine don't seem to be caused by the same reason. The path to my index.js is `[...]\AppData\Roaming\spicetify\CustomApps\name-that-tune\index.js`. 

### 📸 Screenshots

![image](https://github.com/theRealPadster/name-that-tune/assets/37774475/d0745566-4f7a-4a96-b241-4bc6ee2e0da7)
![image](https://github.com/theRealPadster/name-that-tune/assets/37774475/2e36b926-519a-4d35-89c5-4bf925c7d86a)

**Comment by Roaring1** [comment]
this happens for me as well.

**Comment by Mewtwo24** [comment]
I have the same exact error as well.

**Comment by theRealPadster** [comment]
Hmm. It looks like it's an issue with the build process. The bug was supposed to be fixed with Spicetify-Creator 1.0.16, but for some reason it's still happening...

**Comment by theRealPadster** [comment]
I've made some changes and it should work now. Can you download the latest version and try again @Yusuf-Duran ?

**Comment by Mewtwo24** [comment]
The app seems to work now - it does show the following error message when trying to use, but still works properly. The app doesn't seem to be usable when a playlist is directly right-clicked on, but works when a song within the playlist is played first - it starts off with that original song and then goes through the rest of the playlist randomly .
![image](https://github.com/theRealPadster/name-that-tune/assets/42148693/13795dbd-256e-4a87-900b-3a667c5e9ed0)

**Comment by theRealPadster** [comment]
@Mewtwo24 Hmm, can you add that as a separate issue on GitHub? Seems unrelated to this one, which I will close now.
