### ISSUE TITLE
Put Request Fail

### ISSUE THREAD

**Issue by Mewtwo24** [theRealPadster/name-that-tune#53]
#51 

🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.24.756.g7a7fc7f0
- Spicetify version: 2.27.0
```

### 📝 Description

This error message shows up any time Name That Tune is invoked in any circumstance.
![image](https://github.com/theRealPadster/name-that-tune/assets/42148693/13795dbd-256e-4a87-900b-3a667c5e9ed0)

**Comment by theRealPadster** [comment]
@Mewtwo24 Can you update and check if it works now?
