### ISSUE TITLE
guess button don't work

### ISSUE THREAD

**Issue by ShaleveHakime** [theRealPadster/name-that-tune#71]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.26.1187.g36b715a1
Spicetify v2.28.1
Theme: Bloom / comfy
Extensions: adblock.js, fullAlbumDate.js, imageOpener.js, spotifyGenres.js, power-bar.js, volumePercentageWrapper.js, scannables.js, wikify.js, QueueTime.js, playing-source.js, beautiful-lyrics.js, theme.js
Custom apps: marketplace, ncs-visualizer, stats, name-that-tune
```

### 📝 Description

when I press the "guess" button after I typed my guess it just do nothing

### 📸 Screenshots

https://github.com/theRealPadster/name-that-tune/assets/136990507/1f2869fb-c598-4074-8189-371d48dccc3c

**Comment by theRealPadster** [comment]
Oof yeah that's not ideal. Does it work if you press the enter key instead? I'll take a look when I have a chance

**Comment by theRealPadster** [comment]
Do you get any error messages in the dev tools console (after enabling verbose mode)? When I test it myself, the button works. It doesn't do anything if the text entry is empty. 
<img width="803" alt="image" src="https://github.com/theRealPadster/name-that-tune/assets/1565883/fcb56b5c-3198-434d-87a1-6765ac4b5d0c">

**Comment by ShaleveHakime** [comment]
> Oof yeah that's not ideal. Does it work if you press the enter key instead? I'll take a look when I have a chance

no



> Do you get any error messages in the dev tools console (after enabling verbose mode)? When I test it myself, the button works. It doesn't do anything if the text entry is empty. 

yeah, here 
![image](https://github.com/theRealPadster/name-that-tune/assets/136990507/9c1e2cce-00b4-4472-bc8e-fdc897775577)

**Comment by theRealPadster** [comment]
That looks like it's complaining about `Spicetify.Player.data.item?.metadata?.title` in the `checkGuess` function. It used to be `Spicetify.Player.data.track?.metadata?.title`, but was changed in https://github.com/theRealPadster/name-that-tune/pull/54.

Can you run `Spicetify.Player.data.item?.metadata?.title` and `Spicetify.Player.data.item?.metadata?.title` in the console and post the result? 
<img width="338" alt="image" src="https://github.com/theRealPadster/name-that-tune/assets/1565883/44900109-8825-4b06-b92f-dd7639fd6ffd">

I am running  with the save versions as you are:
> Spotify for macOS (Apple Silicon)
> 1.2.26.1187.g36b715a1
> Spicetify v2.28.1

**Comment by ShaleveHakime** [comment]
![image](https://github.com/theRealPadster/name-that-tune/assets/136990507/b6811316-257d-4acc-9373-de6487eb2dba)

**Comment by theRealPadster** [comment]
Can you click the link at the "at mi" part and screenshot that? If it's got a value then maybe it's a different part of the code than I'm thinking?

**Comment by ShaleveHakime** [comment]
![image](https://github.com/theRealPadster/name-that-tune/assets/136990507/a66f647f-3fd1-4526-8cc8-e018159d875d)

**Comment by ShaleveHakime** [comment]
how do i update?

**Comment by theRealPadster** [comment]
Delete the name-that-tune folder and reinstall it. It will retain your data. I just added a Github release so it's easier for people to track version changes in the future. https://github.com/theRealPadster/name-that-tune/releases/tag/0.1.3

**Comment by ShaleveHakime** [comment]
its ok now thanks!
