### ISSUE TITLE
Index.js cant be found

### ISSUE THREAD

**Issue by HimmlischesIQ** [theRealPadster/name-that-tune#99]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
C:\Users\HimmlischesIQ>spicetify apply
spicetify v2.36.11
info Spicetify up-to-date
Overwriting themed assets:
OK
success Custom CSS is updated
Applying additional modifications:
OK
Transferring custom apps:
error Custom app "name-that-tune" does not have index.js
OK
success Spotify is spiced up!


""No Index.js can befound""
Latest Version of Spotify + Spicetify + name-that-tune
```

### 📝 Description

Microsoft Windows [Version 10.0.19045.4412]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\HimmlischesIQ>spicetify config custom_apps name-that-tune
success Config changed: custom_apps = marketplace|name-that-tune
info Run "spicetify apply" to apply new config

C:\Users\HimmlischesIQ>spicetify apply
spicetify v2.36.11
info Spicetify up-to-date
Overwriting themed assets:
OK
success Custom CSS is updated
Applying additional modifications:
OK
Transferring custom apps:
error Custom app "name-that-tune" does not have index.js
OK
success Spotify is spiced up!

C:\Users\HimmlischesIQ>

**Comment by HimmlischesIQ** [comment]
Found the solution...

**Comment by theRealPadster** [comment]
Installed incorrectly.
